name: Node CI

on: 
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Vuepress global
      run: yarn global add vuepress
    - name: Yarn install
      run: yarn install
    - name: build
      run: yarn run docs:build
    - name: deploy
      if: success()
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/.vuepress/dist
        
